language: python
dist: xenial
python:
    - "3.7"
install:
    # Install kpet using pip to ensure dependencies are downloaded correctly.
    - pip install .[dev]
script:
    - tox -e py,coverage
    - pip uninstall -y kpet
